FROM node:20-alpine

WORKDIR /app

# Copy package descriptors first to cache node_modules installation
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy code
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]
